window.CATALOG_DATA = {
  "sourceFile": "2026-1 F.Listesi_Google.xlsx",
  "currency": "TL",
  "priceNote": "Gösterilen fiyatlar liste fiyatlarıdır. İskonto seçildiğinde tüm liste fiyatları aynı oranla güncellenir.",
  "discounts": [
    10,
    15,
    20,
    25,
    30,
    35,
    40,
    45,
    50
  ],
  "products": [
    {
      "id": "2-dlt-4127",
      "row": 2,
      "code": "DLT 4127",
      "name": "Naturella Scabas Fırçalı Kenar Kırma French Set",
      "size": "1.2cm French Set",
      "listPrice": 2100.0,
      "sourceCategory": "Traverten Koleksiyonu",
      "mainCategory": "TRAVERTINE",
      "sortGroup": 1,
      "image": "assets/row-2.png",
      "searchText": "dlt 4127 naturella scabas fırçalı kenar kırma french set 1.2cm french set traverten koleksiyonu travertine"
    },
    {
      "id": "3-dlt-4140",
      "row": 3,
      "code": "DLT 4140",
      "name": "Klasik Eskitme French Set",
      "size": "1.2cm French Set",
      "listPrice": 1990.0,
      "sourceCategory": "Traverten Koleksiyonu",
      "mainCategory": "TRAVERTINE",
      "sortGroup": 1,
      "image": "assets/row-3.png",
      "searchText": "dlt 4140 klasik eskitme french set 1.2cm french set traverten koleksiyonu travertine"
    },
    {
      "id": "4-dlt-4156",
      "row": 4,
      "code": "DLT 4156",
      "name": "Silver Eskitme French Set",
      "size": "1.2cm French Set",
      "listPrice": 2100.0,
      "sourceCategory": "Traverten Koleksiyonu",
      "mainCategory": "TRAVERTINE",
      "sortGroup": 1,
      "image": "assets/row-4.png",
      "searchText": "dlt 4156 silver eskitme french set 1.2cm french set traverten koleksiyonu travertine"
    },
    {
      "id": "5-dlt-4151",
      "row": 5,
      "code": "DLT 4151",
      "name": "Noce Fırçalı Kenar Kırma French Set",
      "size": "1.2cm French Set",
      "listPrice": 2100.0,
      "sourceCategory": "Traverten Koleksiyonu",
      "mainCategory": "TRAVERTINE",
      "sortGroup": 1,
      "image": "assets/row-5.png",
      "searchText": "dlt 4151 noce fırçalı kenar kırma french set 1.2cm french set traverten koleksiyonu travertine"
    },
    {
      "id": "6-dlt-4399",
      "row": 6,
      "code": "DLT 4399",
      "name": "Klasik Export Eskitme French Set",
      "size": "1.2cm French Set",
      "listPrice": 2100.0,
      "sourceCategory": "Traverten Koleksiyonu",
      "mainCategory": "TRAVERTINE",
      "sortGroup": 1,
      "image": "assets/row-6.png",
      "searchText": "dlt 4399 klasik export eskitme french set 1.2cm french set traverten koleksiyonu travertine"
    },
    {
      "id": "7-dlt-4128",
      "row": 7,
      "code": "DLT 4128",
      "name": "Klasik Traverten Eskitme",
      "size": "1x10x10cm",
      "listPrice": 1500.0,
      "sourceCategory": "Küçük Ölçü Traverten Eskitme",
      "mainCategory": "TRAVERTINE",
      "sortGroup": 1,
      "image": "assets/row-7.png",
      "searchText": "dlt 4128 klasik traverten eskitme 1x10x10cm küçük ölçü traverten eskitme travertine"
    },
    {
      "id": "8-dlt-4188",
      "row": 8,
      "code": "DLT 4188",
      "name": "Klasik Traverten Eskitme",
      "size": "1x7.5x15cm",
      "listPrice": 1500.0,
      "sourceCategory": "Küçük Ölçü Traverten Eskitme",
      "mainCategory": "TRAVERTINE",
      "sortGroup": 1,
      "image": "assets/row-8.png",
      "searchText": "dlt 4188 klasik traverten eskitme 1x7.5x15cm küçük ölçü traverten eskitme travertine"
    },
    {
      "id": "9-dlt-4147",
      "row": 9,
      "code": "DLT 4147",
      "name": "Klasik Traverten Eskitme",
      "size": "1x15x15cm",
      "listPrice": 1500.0,
      "sourceCategory": "Küçük Ölçü Traverten Eskitme",
      "mainCategory": "TRAVERTINE",
      "sortGroup": 1,
      "image": "assets/row-9.png",
      "searchText": "dlt 4147 klasik traverten eskitme 1x15x15cm küçük ölçü traverten eskitme travertine"
    },
    {
      "id": "10-dlt-4185",
      "row": 10,
      "code": "DLT 4185",
      "name": "Silver Traverten Eskitme",
      "size": "1x10x10cm",
      "listPrice": 1500.0,
      "sourceCategory": "Küçük Ölçü Traverten Eskitme",
      "mainCategory": "TRAVERTINE",
      "sortGroup": 1,
      "image": "assets/row-10.png",
      "searchText": "dlt 4185 silver traverten eskitme 1x10x10cm küçük ölçü traverten eskitme travertine"
    },
    {
      "id": "11-dlt-4187",
      "row": 11,
      "code": "DLT 4187",
      "name": "Silver Traverten Eskitme",
      "size": "1x7.5x15cm",
      "listPrice": 1500.0,
      "sourceCategory": "Küçük Ölçü Traverten Eskitme",
      "mainCategory": "TRAVERTINE",
      "sortGroup": 1,
      "image": "assets/row-11.png",
      "searchText": "dlt 4187 silver traverten eskitme 1x7.5x15cm küçük ölçü traverten eskitme travertine"
    },
    {
      "id": "12-dlt-4186",
      "row": 12,
      "code": "DLT 4186",
      "name": "Silver Traverten Eskitme",
      "size": "1x15x15cm",
      "listPrice": 1500.0,
      "sourceCategory": "Küçük Ölçü Traverten Eskitme",
      "mainCategory": "TRAVERTINE",
      "sortGroup": 1,
      "image": "assets/row-12.png",
      "searchText": "dlt 4186 silver traverten eskitme 1x15x15cm küçük ölçü traverten eskitme travertine"
    },
    {
      "id": "13-dlt-5341",
      "row": 13,
      "code": "DLT 5341",
      "name": "Bej Eskitme",
      "size": "1.2x7.5x15cm",
      "listPrice": 1500.0,
      "sourceCategory": "Küçük Ölçü Traverten Eskitme",
      "mainCategory": "TRAVERTINE",
      "sortGroup": 1,
      "image": "",
      "searchText": "dlt 5341 bej eskitme 1.2x7.5x15cm küçük ölçü traverten eskitme travertine"
    },
    {
      "id": "14-dlt-5397",
      "row": 14,
      "code": "DLT 5397",
      "name": "Blue Stone Eskitme",
      "size": "1x10x10cm",
      "listPrice": 2000.0,
      "sourceCategory": "Küçük Ölçü Traverten Eskitme",
      "mainCategory": "TRAVERTINE",
      "sortGroup": 1,
      "image": "assets/row-14.png",
      "searchText": "dlt 5397 blue stone eskitme 1x10x10cm küçük ölçü traverten eskitme travertine"
    },
    {
      "id": "15-dlt-5299",
      "row": 15,
      "code": "DLT 5299",
      "name": "Bej Eskitme",
      "size": "1.2x10x10cm",
      "listPrice": 1500.0,
      "sourceCategory": "Küçük Ölçü Traverten Eskitme",
      "mainCategory": "TRAVERTINE",
      "sortGroup": 1,
      "image": "assets/row-15.png",
      "searchText": "dlt 5299 bej eskitme 1.2x10x10cm küçük ölçü traverten eskitme travertine"
    },
    {
      "id": "16-dlt-1153",
      "row": 16,
      "code": "DLT 1153",
      "name": "Silver Patlatma Mozaik",
      "size": "1.7x4.8x10cm",
      "listPrice": 1520.0,
      "sourceCategory": "Patlatma Mozaik Koleksiyonu",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-16.png",
      "searchText": "dlt 1153 silver patlatma mozaik 1.7x4.8x10cm patlatma mozaik koleksiyonu splitface & mosaics"
    },
    {
      "id": "17-dlt-1122",
      "row": 17,
      "code": "DLT 1122",
      "name": "Sarı Patlatma Mozaik",
      "size": "1.2x2.3x4.8cm",
      "listPrice": 2050.0,
      "sourceCategory": "2.3x4.8cm Patlatma Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-17.png",
      "searchText": "dlt 1122 sarı patlatma mozaik 1.2x2.3x4.8cm 2.3x4.8cm patlatma mozaik splitface & mosaics"
    },
    {
      "id": "18-dlt-1132",
      "row": 18,
      "code": "DLT 1132",
      "name": "Toros Patlatma Mozaik",
      "size": "1.2x2.3x4.8cm",
      "listPrice": 1990.0,
      "sourceCategory": "2.3x4.8cm Patlatma Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-18.png",
      "searchText": "dlt 1132 toros patlatma mozaik 1.2x2.3x4.8cm 2.3x4.8cm patlatma mozaik splitface & mosaics"
    },
    {
      "id": "19-dlt-1205",
      "row": 19,
      "code": "DLT 1205",
      "name": "Odessa Patlatma Mozaik",
      "size": "1.2x2.3x4.8cm",
      "listPrice": 1520.0,
      "sourceCategory": "2.3x4.8cm Patlatma Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-19.png",
      "searchText": "dlt 1205 odessa patlatma mozaik 1.2x2.3x4.8cm 2.3x4.8cm patlatma mozaik splitface & mosaics"
    },
    {
      "id": "20-dlt-1110",
      "row": 20,
      "code": "DLT 1110",
      "name": "Miks Patlatma Mozaik",
      "size": "1.2x2.3x4.8cm",
      "listPrice": 1520.0,
      "sourceCategory": "2.3x4.8cm Patlatma Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-20.png",
      "searchText": "dlt 1110 miks patlatma mozaik 1.2x2.3x4.8cm 2.3x4.8cm patlatma mozaik splitface & mosaics"
    },
    {
      "id": "21-dlt-1118",
      "row": 21,
      "code": "DLT 1118",
      "name": "Beyaz Patlatma Mozaik",
      "size": "1.2x2.3x4.8cm",
      "listPrice": 1520.0,
      "sourceCategory": "2.3x4.8cm Patlatma Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-21.png",
      "searchText": "dlt 1118 beyaz patlatma mozaik 1.2x2.3x4.8cm 2.3x4.8cm patlatma mozaik splitface & mosaics"
    },
    {
      "id": "22-dlt-1119",
      "row": 22,
      "code": "DLT 1119",
      "name": "Bardiglio Patlatma Mozaik",
      "size": "1.2x2.3x4.8cm",
      "listPrice": 1520.0,
      "sourceCategory": "2.3x4.8cm Patlatma Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-22.png",
      "searchText": "dlt 1119 bardiglio patlatma mozaik 1.2x2.3x4.8cm 2.3x4.8cm patlatma mozaik splitface & mosaics"
    },
    {
      "id": "23-dlt-1525",
      "row": 23,
      "code": "DLT 1525",
      "name": "Klasik Patlatma Mozaik",
      "size": "1.2x2.3x4.8cm",
      "listPrice": 1400.0,
      "sourceCategory": "2.3x4.8cm Patlatma Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-23.png",
      "searchText": "dlt 1525 klasik patlatma mozaik 1.2x2.3x4.8cm 2.3x4.8cm patlatma mozaik splitface & mosaics"
    },
    {
      "id": "24-dlt-1124",
      "row": 24,
      "code": "DLT 1124",
      "name": "Silver Patlatma Mozaik",
      "size": "1.2x2.3x4.8cm",
      "listPrice": 1520.0,
      "sourceCategory": "2.3x4.8cm Patlatma Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-24.png",
      "searchText": "dlt 1124 silver patlatma mozaik 1.2x2.3x4.8cm 2.3x4.8cm patlatma mozaik splitface & mosaics"
    },
    {
      "id": "25-dlt-1526",
      "row": 25,
      "code": "DLT 1526",
      "name": "Bej Patlatma Mozaik",
      "size": "1.2x2.3x4.8cm",
      "listPrice": 1520.0,
      "sourceCategory": "2.3x4.8cm Patlatma Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-25.png",
      "searchText": "dlt 1526 bej patlatma mozaik 1.2x2.3x4.8cm 2.3x4.8cm patlatma mozaik splitface & mosaics"
    },
    {
      "id": "26-dlt-1125",
      "row": 26,
      "code": "DLT 1125",
      "name": "Scabas Patlatma Mozaik",
      "size": "1.2x2.3x4.8cm",
      "listPrice": 2050.0,
      "sourceCategory": "2.3x4.8cm Patlatma Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-26.png",
      "searchText": "dlt 1125 scabas patlatma mozaik 1.2x2.3x4.8cm 2.3x4.8cm patlatma mozaik splitface & mosaics"
    },
    {
      "id": "27-dlt-1273",
      "row": 27,
      "code": "DLT 1273",
      "name": "Panama Patlatma Mozaik",
      "size": "1.2x2.3x4.8cm",
      "listPrice": 1520.0,
      "sourceCategory": "2.3x4.8cm Patlatma Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-27.png",
      "searchText": "dlt 1273 panama patlatma mozaik 1.2x2.3x4.8cm 2.3x4.8cm patlatma mozaik splitface & mosaics"
    },
    {
      "id": "28-dlt-1200",
      "row": 28,
      "code": "DLT 1200",
      "name": "Plata Patlatma Mozaik",
      "size": "1.2x2.3x4.8cm",
      "listPrice": 1520.0,
      "sourceCategory": "2.3x4.8cm Patlatma Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-28.png",
      "searchText": "dlt 1200 plata patlatma mozaik 1.2x2.3x4.8cm 2.3x4.8cm patlatma mozaik splitface & mosaics"
    },
    {
      "id": "29-dlt-1121",
      "row": 29,
      "code": "DLT 1121",
      "name": "Klasik Patlatma Mozaik",
      "size": "1.7x4.8x10cm",
      "listPrice": 1520.0,
      "sourceCategory": "4.8x10cm Patlatma Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-29.png",
      "searchText": "dlt 1121 klasik patlatma mozaik 1.7x4.8x10cm 4.8x10cm patlatma mozaik splitface & mosaics"
    },
    {
      "id": "30-dlt-1151",
      "row": 30,
      "code": "DLT 1151",
      "name": "Bej Patlatma Mozaik",
      "size": "1.7x4.8x10cm",
      "listPrice": 1520.0,
      "sourceCategory": "4.8x10cm Patlatma Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-30.png",
      "searchText": "dlt 1151 bej patlatma mozaik 1.7x4.8x10cm 4.8x10cm patlatma mozaik splitface & mosaics"
    },
    {
      "id": "31-dlt-1153",
      "row": 31,
      "code": "DLT 1153",
      "name": "Silver Patlatma Mozaik",
      "size": "1.7x4.8x10cm",
      "listPrice": 1520.0,
      "sourceCategory": "4.8x10cm Patlatma Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "",
      "searchText": "dlt 1153 silver patlatma mozaik 1.7x4.8x10cm 4.8x10cm patlatma mozaik splitface & mosaics"
    },
    {
      "id": "32-dlt-1184",
      "row": 32,
      "code": "DLT 1184",
      "name": "Scabas Patlatma Mozaik",
      "size": "1.7x4.8x10cm",
      "listPrice": 1990.0,
      "sourceCategory": "4.8x10cm Patlatma Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-32.png",
      "searchText": "dlt 1184 scabas patlatma mozaik 1.7x4.8x10cm 4.8x10cm patlatma mozaik splitface & mosaics"
    },
    {
      "id": "33-dlt-1192",
      "row": 33,
      "code": "DLT 1192",
      "name": "Toros Patlatma Mozaik",
      "size": "1.7x4.8x10cm",
      "listPrice": 2100.0,
      "sourceCategory": "4.8x10cm Patlatma Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-33.png",
      "searchText": "dlt 1192 toros patlatma mozaik 1.7x4.8x10cm 4.8x10cm patlatma mozaik splitface & mosaics"
    },
    {
      "id": "34-dlt-1180",
      "row": 34,
      "code": "DLT 1180",
      "name": "Tropica Patlatma Mozaik",
      "size": "1.7x4.8x10cm",
      "listPrice": 1520.0,
      "sourceCategory": "4.8x10cm Patlatma Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-34.png",
      "searchText": "dlt 1180 tropica patlatma mozaik 1.7x4.8x10cm 4.8x10cm patlatma mozaik splitface & mosaics"
    },
    {
      "id": "35-dlt-1191",
      "row": 35,
      "code": "DLT 1191",
      "name": "Miks Patlatma Mozaik",
      "size": "1.7x4.8x10cm",
      "listPrice": 1520.0,
      "sourceCategory": "4.8x10cm Patlatma Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-35.png",
      "searchText": "dlt 1191 miks patlatma mozaik 1.7x4.8x10cm 4.8x10cm patlatma mozaik splitface & mosaics"
    },
    {
      "id": "36-dlt-1210",
      "row": 36,
      "code": "DLT 1210",
      "name": "Naçka Patlatma Mozaik",
      "size": "1.7x4.8x10cm",
      "listPrice": 1990.0,
      "sourceCategory": "4.8x10cm Patlatma Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-36.png",
      "searchText": "dlt 1210 naçka patlatma mozaik 1.7x4.8x10cm 4.8x10cm patlatma mozaik splitface & mosaics"
    },
    {
      "id": "37-dlt-1168-1238",
      "row": 37,
      "code": "DLT 1168/1238",
      "name": "Ledger Kaşgar Silver",
      "size": "1.7x2.3/3.2/4.8x10cm",
      "listPrice": 3850.0,
      "sourceCategory": "Ledger Panel Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-37.png",
      "searchText": "dlt 1168/1238 ledger kaşgar silver 1.7x2.3/3.2/4.8x10cm ledger panel mozaik splitface & mosaics"
    },
    {
      "id": "38-dlt-1196-1252",
      "row": 38,
      "code": "DLT 1196/1252",
      "name": "Ledger Kaşgar Havai",
      "size": "1.7x2.3/3.2/4.8x10cm",
      "listPrice": 3850.0,
      "sourceCategory": "Ledger Panel Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-38.png",
      "searchText": "dlt 1196/1252 ledger kaşgar havai 1.7x2.3/3.2/4.8x10cm ledger panel mozaik splitface & mosaics"
    },
    {
      "id": "39-dlt-1215",
      "row": 39,
      "code": "DLT 1215",
      "name": "Ilıca Klasik Filesiz",
      "size": "1.7x4.8x15cm",
      "listPrice": 1250.0,
      "sourceCategory": "4.8x15cm Filesiz Patlatma",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-39.png",
      "searchText": "dlt 1215 ilıca klasik filesiz 1.7x4.8x15cm 4.8x15cm filesiz patlatma splitface & mosaics"
    },
    {
      "id": "40-dlt-1261",
      "row": 40,
      "code": "DLT 1261",
      "name": "Ilıca Silver Filesiz",
      "size": "1.7x4.8x15cm",
      "listPrice": 1400.0,
      "sourceCategory": "4.8x15cm Filesiz Patlatma",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-40.png",
      "searchText": "dlt 1261 ilıca silver filesiz 1.7x4.8x15cm 4.8x15cm filesiz patlatma splitface & mosaics"
    },
    {
      "id": "41-dlt-1286",
      "row": 41,
      "code": "DLT 1286",
      "name": "Toros Filesiz",
      "size": "2x5x15cm",
      "listPrice": 2000.0,
      "sourceCategory": "4.8x15cm Filesiz Patlatma",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-41.png",
      "searchText": "dlt 1286 toros filesiz 2x5x15cm 4.8x15cm filesiz patlatma splitface & mosaics"
    },
    {
      "id": "42-dlt-1112",
      "row": 42,
      "code": "DLT 1112",
      "name": "Klasik Filesiz",
      "size": "2.5x10xBoy Serbest",
      "listPrice": 1250.0,
      "sourceCategory": "10cmxBoy Serbest Filesiz",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-42.png",
      "searchText": "dlt 1112 klasik filesiz 2.5x10xboy serbest 10cmxboy serbest filesiz splitface & mosaics"
    },
    {
      "id": "43-dlt-1276",
      "row": 43,
      "code": "DLT 1276",
      "name": "Bardiglio Filesiz",
      "size": "2.5x10xBoy Serbest",
      "listPrice": 1400.0,
      "sourceCategory": "10cmxBoy Serbest Filesiz",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-43.png",
      "searchText": "dlt 1276 bardiglio filesiz 2.5x10xboy serbest 10cmxboy serbest filesiz splitface & mosaics"
    },
    {
      "id": "44-dlt-1260",
      "row": 44,
      "code": "DLT 1260",
      "name": "Silver Filesiz",
      "size": "2.5x10xBoy Serbest",
      "listPrice": 1400.0,
      "sourceCategory": "10cmxBoy Serbest Filesiz",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-44.png",
      "searchText": "dlt 1260 silver filesiz 2.5x10xboy serbest 10cmxboy serbest filesiz splitface & mosaics"
    },
    {
      "id": "45-dlt-1292",
      "row": 45,
      "code": "DLT 1292",
      "name": "Blue Stone Filesiz",
      "size": "2.5x7.5xBoy Serbest",
      "listPrice": 2000.0,
      "sourceCategory": "10cmxBoy Serbest Filesiz",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-45.png",
      "searchText": "dlt 1292 blue stone filesiz 2.5x7.5xboy serbest 10cmxboy serbest filesiz splitface & mosaics"
    },
    {
      "id": "46-dlt-9301",
      "row": 46,
      "code": "DLT 9301",
      "name": "Rubble Stone Klasik",
      "size": "2.5x5xAmorf",
      "listPrice": 2100.0,
      "sourceCategory": "Taş Duvar Koleksiyonu",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "",
      "searchText": "dlt 9301 rubble stone klasik 2.5x5xamorf taş duvar koleksiyonu splitface & mosaics"
    },
    {
      "id": "47-dlt-9302",
      "row": 47,
      "code": "DLT 9302",
      "name": "Rubble Stone Bardiglio",
      "size": "2.5x5xAmorf",
      "listPrice": 2100.0,
      "sourceCategory": "Taş Duvar Koleksiyonu",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-47.png",
      "searchText": "dlt 9302 rubble stone bardiglio 2.5x5xamorf taş duvar koleksiyonu splitface & mosaics"
    },
    {
      "id": "48-dlt-9303",
      "row": 48,
      "code": "DLT 9303",
      "name": "Rubble Stone Blue Stone",
      "size": "2.5x5xAmorf",
      "listPrice": 2100.0,
      "sourceCategory": "Taş Duvar Koleksiyonu",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-48.png",
      "searchText": "dlt 9303 rubble stone blue stone 2.5x5xamorf taş duvar koleksiyonu splitface & mosaics"
    },
    {
      "id": "49-dlt-9304",
      "row": 49,
      "code": "DLT 9304",
      "name": "Rubble Stone Silver",
      "size": "2.5x5xAmorf",
      "listPrice": 2100.0,
      "sourceCategory": "Taş Duvar Koleksiyonu",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-49.png",
      "searchText": "dlt 9304 rubble stone silver 2.5x5xamorf taş duvar koleksiyonu splitface & mosaics"
    },
    {
      "id": "50-dlt-9305",
      "row": 50,
      "code": "DLT 9305",
      "name": "Rubble Stone Rustik",
      "size": "2.5x5xAmorf",
      "listPrice": 2100.0,
      "sourceCategory": "Taş Duvar Koleksiyonu",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-50.png",
      "searchText": "dlt 9305 rubble stone rustik 2.5x5xamorf taş duvar koleksiyonu splitface & mosaics"
    },
    {
      "id": "51-dlt-9306",
      "row": 51,
      "code": "DLT 9306",
      "name": "Rubble Stone Noce",
      "size": "2.5x5xAmorf",
      "listPrice": 2100.0,
      "sourceCategory": "Taş Duvar Koleksiyonu",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-51.png",
      "searchText": "dlt 9306 rubble stone noce 2.5x5xamorf taş duvar koleksiyonu splitface & mosaics"
    },
    {
      "id": "52-dlt-9307",
      "row": 52,
      "code": "DLT 9307",
      "name": "Rubble Stone Sarı",
      "size": "2.5x5xAmorf",
      "listPrice": 3850.0,
      "sourceCategory": "Taş Duvar Koleksiyonu",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-52.png",
      "searchText": "dlt 9307 rubble stone sarı 2.5x5xamorf taş duvar koleksiyonu splitface & mosaics"
    },
    {
      "id": "53-dlt-9308",
      "row": 53,
      "code": "DLT 9308",
      "name": "Rubble Stone Bazalt",
      "size": "2.5x5xAmorf",
      "listPrice": 2100.0,
      "sourceCategory": "Taş Duvar Koleksiyonu",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-53.png",
      "searchText": "dlt 9308 rubble stone bazalt 2.5x5xamorf taş duvar koleksiyonu splitface & mosaics"
    },
    {
      "id": "54-dlt-2101",
      "row": 54,
      "code": "DLT 2101",
      "name": "Klasik Traverten Taraklı Mozaik",
      "size": "1.7x5x10cm",
      "listPrice": 4920.0,
      "sourceCategory": "Taraklı Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-54.png",
      "searchText": "dlt 2101 klasik traverten taraklı mozaik 1.7x5x10cm taraklı mozaik splitface & mosaics"
    },
    {
      "id": "55-dlt-2106",
      "row": 55,
      "code": "DLT 2106",
      "name": "Siyah Taraklı Mozaik",
      "size": "1.7x5x5cm",
      "listPrice": 4920.0,
      "sourceCategory": "Taraklı Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-55.png",
      "searchText": "dlt 2106 siyah taraklı mozaik 1.7x5x5cm taraklı mozaik splitface & mosaics"
    },
    {
      "id": "56-dlt-2534",
      "row": 56,
      "code": "DLT 2534",
      "name": "Klasik Traverten Taraklı Mozaik 2",
      "size": "1.7x5x5cm",
      "listPrice": 4920.0,
      "sourceCategory": "Taraklı Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-56.png",
      "searchText": "dlt 2534 klasik traverten taraklı mozaik 2 1.7x5x5cm taraklı mozaik splitface & mosaics"
    },
    {
      "id": "57-dlt-2177",
      "row": 57,
      "code": "DLT 2177",
      "name": "Silver Bambu Mozaik",
      "size": "2x1.5x7.5cm",
      "listPrice": 5700.0,
      "sourceCategory": "Bambu Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-57.png",
      "searchText": "dlt 2177 silver bambu mozaik 2x1.5x7.5cm bambu mozaik splitface & mosaics"
    },
    {
      "id": "58-dlt-2178",
      "row": 58,
      "code": "DLT 2178",
      "name": "Scabas Bambu Mozaik",
      "size": "2x1.5x7.5cm",
      "listPrice": 5700.0,
      "sourceCategory": "Bambu Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-58.png",
      "searchText": "dlt 2178 scabas bambu mozaik 2x1.5x7.5cm bambu mozaik splitface & mosaics"
    },
    {
      "id": "59-dlt-2186",
      "row": 59,
      "code": "DLT 2186",
      "name": "Violet Bambu Mozaik",
      "size": "2x1.5x7.5cm",
      "listPrice": 5700.0,
      "sourceCategory": "Bambu Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-59.png",
      "searchText": "dlt 2186 violet bambu mozaik 2x1.5x7.5cm bambu mozaik splitface & mosaics"
    },
    {
      "id": "60-dlt-2184",
      "row": 60,
      "code": "DLT 2184",
      "name": "Jambi Silver Bambu Mozaik",
      "size": "2x1.5x7.5cm",
      "listPrice": 5700.0,
      "sourceCategory": "Bambu Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-60.png",
      "searchText": "dlt 2184 jambi silver bambu mozaik 2x1.5x7.5cm bambu mozaik splitface & mosaics"
    },
    {
      "id": "61-dlt-2185",
      "row": 61,
      "code": "DLT 2185",
      "name": "Jambi Scabas Bambu Mozaik",
      "size": "2x1.5x7.5cm",
      "listPrice": 5700.0,
      "sourceCategory": "Bambu Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-61.png",
      "searchText": "dlt 2185 jambi scabas bambu mozaik 2x1.5x7.5cm bambu mozaik splitface & mosaics"
    },
    {
      "id": "62-dlt-2109",
      "row": 62,
      "code": "DLT 2109",
      "name": "Klasik Hasır Konkav Mozaik",
      "size": "2x4.8x4.8cm",
      "listPrice": 4920.0,
      "sourceCategory": "Konkav Mozaik 4.8x4.8cm",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-62.png",
      "searchText": "dlt 2109 klasik hasır konkav mozaik 2x4.8x4.8cm konkav mozaik 4.8x4.8cm splitface & mosaics"
    },
    {
      "id": "63-dlt-2118",
      "row": 63,
      "code": "DLT 2118",
      "name": "Violet Konkav Mozaik",
      "size": "2x4.8x4.8cm",
      "listPrice": 4920.0,
      "sourceCategory": "Konkav Mozaik 4.8x4.8cm",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-63.png",
      "searchText": "dlt 2118 violet konkav mozaik 2x4.8x4.8cm konkav mozaik 4.8x4.8cm splitface & mosaics"
    },
    {
      "id": "64-dlt-2127",
      "row": 64,
      "code": "DLT 2127",
      "name": "Farah Klasik Konkav Mozaik",
      "size": "2x9.5x9.5cm",
      "listPrice": 4920.0,
      "sourceCategory": "Konkav Mozaik 9.5x9.5cm",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-64.png",
      "searchText": "dlt 2127 farah klasik konkav mozaik 2x9.5x9.5cm konkav mozaik 9.5x9.5cm splitface & mosaics"
    },
    {
      "id": "65-dlt-2183",
      "row": 65,
      "code": "DLT 2183",
      "name": "Farah Diana Bej Konkav Mozaik",
      "size": "2x9.5x9.5cm",
      "listPrice": 4920.0,
      "sourceCategory": "Konkav Mozaik 9.5x9.5cm",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-65.png",
      "searchText": "dlt 2183 farah diana bej konkav mozaik 2x9.5x9.5cm konkav mozaik 9.5x9.5cm splitface & mosaics"
    },
    {
      "id": "66-dlt-2152",
      "row": 66,
      "code": "DLT 2152",
      "name": "Farah Violet Konkav Mozaik",
      "size": "2x9.5x9.5cm",
      "listPrice": 4920.0,
      "sourceCategory": "Konkav Mozaik 9.5x9.5cm",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-66.png",
      "searchText": "dlt 2152 farah violet konkav mozaik 2x9.5x9.5cm konkav mozaik 9.5x9.5cm splitface & mosaics"
    },
    {
      "id": "67-dlt-2153",
      "row": 67,
      "code": "DLT 2153",
      "name": "Farah Toros Konkav Mozaik",
      "size": "2x9.5x9.5cm",
      "listPrice": 10500.0,
      "sourceCategory": "Konkav Mozaik 9.5x9.5cm",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-67.png",
      "searchText": "dlt 2153 farah toros konkav mozaik 2x9.5x9.5cm konkav mozaik 9.5x9.5cm splitface & mosaics"
    },
    {
      "id": "68-dlt-2128",
      "row": 68,
      "code": "DLT 2128",
      "name": "Farah Tundra Konkav Mozaik",
      "size": "2x9.5x9.5cm",
      "listPrice": 4920.0,
      "sourceCategory": "Konkav Mozaik 9.5x9.5cm",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-68.png",
      "searchText": "dlt 2128 farah tundra konkav mozaik 2x9.5x9.5cm konkav mozaik 9.5x9.5cm splitface & mosaics"
    },
    {
      "id": "69-dlt-3289",
      "row": 69,
      "code": "DLT 3289",
      "name": "Reşadiye Bal Peteği Mozaik",
      "size": "1x4.8cm",
      "listPrice": 6450.0,
      "sourceCategory": "Bal Peteği Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-69.png",
      "searchText": "dlt 3289 reşadiye bal peteği mozaik 1x4.8cm bal peteği mozaik splitface & mosaics"
    },
    {
      "id": "70-dlt-3377",
      "row": 70,
      "code": "DLT 3377",
      "name": "Liberya Bal Peteği Mozaik",
      "size": "1x4.8cm",
      "listPrice": 6450.0,
      "sourceCategory": "Bal Peteği Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "",
      "searchText": "dlt 3377 liberya bal peteği mozaik 1x4.8cm bal peteği mozaik splitface & mosaics"
    },
    {
      "id": "71-dlt-3193",
      "row": 71,
      "code": "DLT 3193",
      "name": "Carrera Bal Peteği Mozaik",
      "size": "1x4.8cm",
      "listPrice": 6450.0,
      "sourceCategory": "Bal Peteği Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-71.png",
      "searchText": "dlt 3193 carrera bal peteği mozaik 1x4.8cm bal peteği mozaik splitface & mosaics"
    },
    {
      "id": "72-dlt-3270",
      "row": 72,
      "code": "DLT 3270",
      "name": "Selanik Bal Peteği Mozaik",
      "size": "1x4.8cm",
      "listPrice": 6450.0,
      "sourceCategory": "Bal Peteği Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-72.png",
      "searchText": "dlt 3270 selanik bal peteği mozaik 1x4.8cm bal peteği mozaik splitface & mosaics"
    },
    {
      "id": "73-dlt-3282",
      "row": 73,
      "code": "DLT 3282",
      "name": "Toros Bal Peteği Mozaik",
      "size": "1x4.8cm",
      "listPrice": 10500.0,
      "sourceCategory": "Bal Peteği Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-73.png",
      "searchText": "dlt 3282 toros bal peteği mozaik 1x4.8cm bal peteği mozaik splitface & mosaics"
    },
    {
      "id": "74-dlt-578",
      "row": 74,
      "code": "DLT 578",
      "name": "Crown 3 Profil",
      "size": "5x2.5x30.5cm",
      "listPrice": 270.0,
      "sourceCategory": "Profil",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-74.png",
      "searchText": "dlt 578 crown 3 profil 5x2.5x30.5cm profil splitface & mosaics"
    },
    {
      "id": "75-dlt-580",
      "row": 75,
      "code": "DLT 580",
      "name": "Pencil Profil",
      "size": "2x1.4x30.5cm",
      "listPrice": 250.0,
      "sourceCategory": "Profil",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-75.png",
      "searchText": "dlt 580 pencil profil 2x1.4x30.5cm profil splitface & mosaics"
    },
    {
      "id": "76-dlt-3256",
      "row": 76,
      "code": "DLT 3256",
      "name": "Klasik Arabeskato Mozaik",
      "size": "1x4.8x4.8cm Honlu",
      "listPrice": 5700.0,
      "sourceCategory": "Arabeskato Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-76.png",
      "searchText": "dlt 3256 klasik arabeskato mozaik 1x4.8x4.8cm honlu arabeskato mozaik splitface & mosaics"
    },
    {
      "id": "77-dlt-3266",
      "row": 77,
      "code": "DLT 3266",
      "name": "Silver Arabeskato Mozaik",
      "size": "1x4.8x4.8cm Honlu",
      "listPrice": 5700.0,
      "sourceCategory": "Arabeskato Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-77.png",
      "searchText": "dlt 3266 silver arabeskato mozaik 1x4.8x4.8cm honlu arabeskato mozaik splitface & mosaics"
    },
    {
      "id": "78-dlt-3307",
      "row": 78,
      "code": "DLT 3307",
      "name": "Diana Bej Arabeskato Mozaik",
      "size": "1x4.8x4.8cm Cila",
      "listPrice": 5700.0,
      "sourceCategory": "Arabeskato Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-78.png",
      "searchText": "dlt 3307 diana bej arabeskato mozaik 1x4.8x4.8cm cila arabeskato mozaik splitface & mosaics"
    },
    {
      "id": "79-dlt-3498",
      "row": 79,
      "code": "DLT 3498",
      "name": "Carrera Arabeskato Mozaik",
      "size": "1x4.8x4.8cm Cila",
      "listPrice": 5700.0,
      "sourceCategory": "Arabeskato Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-79.png",
      "searchText": "dlt 3498 carrera arabeskato mozaik 1x4.8x4.8cm cila arabeskato mozaik splitface & mosaics"
    },
    {
      "id": "80-dlt-3258",
      "row": 80,
      "code": "DLT 3258",
      "name": "Tundra Arabeskato Mozaik",
      "size": "1x4.8x4.8cm Cila",
      "listPrice": 5700.0,
      "sourceCategory": "Arabeskato Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-80.png",
      "searchText": "dlt 3258 tundra arabeskato mozaik 1x4.8x4.8cm cila arabeskato mozaik splitface & mosaics"
    },
    {
      "id": "81-dlt-3221",
      "row": 81,
      "code": "DLT 3221",
      "name": "Blue Stone Eskitme Mozaik",
      "size": "1x4.8x4.8cm",
      "listPrice": 3850.0,
      "sourceCategory": "Eskitme Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-81.png",
      "searchText": "dlt 3221 blue stone eskitme mozaik 1x4.8x4.8cm eskitme mozaik splitface & mosaics"
    },
    {
      "id": "82-dlt-3241",
      "row": 82,
      "code": "DLT 3241",
      "name": "Java Chevron Mozaik",
      "size": "1x1.5/3.2x7.5cm",
      "listPrice": 8600.0,
      "sourceCategory": "Chevron Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-82.png",
      "searchText": "dlt 3241 java chevron mozaik 1x1.5/3.2x7.5cm chevron mozaik splitface & mosaics"
    },
    {
      "id": "83-dlt-3271",
      "row": 83,
      "code": "DLT 3271",
      "name": "Salvador Chevron Mozaik",
      "size": "1x1.5/3.2x7.5cm",
      "listPrice": 8600.0,
      "sourceCategory": "Chevron Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-83.png",
      "searchText": "dlt 3271 salvador chevron mozaik 1x1.5/3.2x7.5cm chevron mozaik splitface & mosaics"
    },
    {
      "id": "84-dlt-3251",
      "row": 84,
      "code": "DLT 3251",
      "name": "Dolamite Chevron Mozaik",
      "size": "1x1.5/3.2x7.5cm",
      "listPrice": 15000.0,
      "sourceCategory": "Chevron Mozaik",
      "mainCategory": "SPLITFACE & MOSAICS",
      "sortGroup": 2,
      "image": "assets/row-84.png",
      "searchText": "dlt 3251 dolamite chevron mozaik 1x1.5/3.2x7.5cm chevron mozaik splitface & mosaics"
    },
    {
      "id": "85-dlt-708-01",
      "row": 85,
      "code": "DLT 708-01",
      "name": "Porto Klasik Lavabo",
      "size": "15x45x60cm",
      "listPrice": 10400.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-85.png",
      "searchText": "dlt 708-01 porto klasik lavabo 15x45x60cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "86-dlt-618-01",
      "row": 86,
      "code": "DLT 618-01",
      "name": "Zürih Klasik Lavabo",
      "size": "15x42cm",
      "listPrice": 7850.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-86.png",
      "searchText": "dlt 618-01 zürih klasik lavabo 15x42cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "87-dlt-618-15",
      "row": 87,
      "code": "DLT 618-15",
      "name": "Zürih Beyaz Lavabo",
      "size": "15x42cm",
      "listPrice": 7850.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-87.png",
      "searchText": "dlt 618-15 zürih beyaz lavabo 15x42cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "88-dlt-618-19",
      "row": 88,
      "code": "DLT 618-19",
      "name": "Zürih Toros Lavabo",
      "size": "15x42cm",
      "listPrice": 14500.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-88.png",
      "searchText": "dlt 618-19 zürih toros lavabo 15x42cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "89-dlt-626-01",
      "row": 89,
      "code": "DLT 626-01",
      "name": "Roma Klasik Lavabo",
      "size": "15x42cm",
      "listPrice": 7850.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-89.png",
      "searchText": "dlt 626-01 roma klasik lavabo 15x42cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "90-dlt-626-13",
      "row": 90,
      "code": "DLT 626-13",
      "name": "Roma Bardiglio Lavabo",
      "size": "15x42cm",
      "listPrice": 7850.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-90.png",
      "searchText": "dlt 626-13 roma bardiglio lavabo 15x42cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "91-dlt-626-19",
      "row": 91,
      "code": "DLT 626-19",
      "name": "Roma Toros Lavabo",
      "size": "15x42cm",
      "listPrice": 14500.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-91.png",
      "searchText": "dlt 626-19 roma toros lavabo 15x42cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "92-dlt-622-01",
      "row": 92,
      "code": "DLT 622-01",
      "name": "Paris Klasik Lavabo",
      "size": "15x42cm",
      "listPrice": 7850.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-92.png",
      "searchText": "dlt 622-01 paris klasik lavabo 15x42cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "93-dlt-629-01",
      "row": 93,
      "code": "DLT 629-01",
      "name": "Atina Klasik Lavabo",
      "size": "15x42cm",
      "listPrice": 7850.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-93.png",
      "searchText": "dlt 629-01 atina klasik lavabo 15x42cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "94-dlt-629-25",
      "row": 94,
      "code": "DLT 629-25",
      "name": "Atina Silver Lavabo",
      "size": "15x42cm",
      "listPrice": 7850.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-94.png",
      "searchText": "dlt 629-25 atina silver lavabo 15x42cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "95-dlt-630-01",
      "row": 95,
      "code": "DLT 630-01",
      "name": "Viyana Klasik Lavabo",
      "size": "15x42cm",
      "listPrice": 7850.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-95.png",
      "searchText": "dlt 630-01 viyana klasik lavabo 15x42cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "96-dlt-630-02",
      "row": 96,
      "code": "DLT 630-02",
      "name": "Viyana Noce Lavabo",
      "size": "15x42cm",
      "listPrice": 7850.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-96.png",
      "searchText": "dlt 630-02 viyana noce lavabo 15x42cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "97-dlt-630-25",
      "row": 97,
      "code": "DLT 630-25",
      "name": "Viyana Silver Lavabo",
      "size": "15x42cm",
      "listPrice": 7850.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-97.png",
      "searchText": "dlt 630-25 viyana silver lavabo 15x42cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "98-dlt-721-01",
      "row": 98,
      "code": "DLT 721-01",
      "name": "Kufe Klasik Lavabo",
      "size": "15x42cm",
      "listPrice": 7850.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-98.png",
      "searchText": "dlt 721-01 kufe klasik lavabo 15x42cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "99-dlt-731-23",
      "row": 99,
      "code": "DLT 731-23",
      "name": "Sevilla Bazalt Lavabo",
      "size": "15x42cm",
      "listPrice": 10400.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-99.png",
      "searchText": "dlt 731-23 sevilla bazalt lavabo 15x42cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "100-dlt-734-01",
      "row": 100,
      "code": "DLT 734-01",
      "name": "Kyoto Klasik Lavabo",
      "size": "12x45cm",
      "listPrice": 10400.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-100.png",
      "searchText": "dlt 734-01 kyoto klasik lavabo 12x45cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "101-dlt-746-15",
      "row": 101,
      "code": "DLT 746-15",
      "name": "Galata Beyaz Lavabo",
      "size": "38x65cm",
      "listPrice": 10400.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-101.png",
      "searchText": "dlt 746-15 galata beyaz lavabo 38x65cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "102-dlt-746-25",
      "row": 102,
      "code": "DLT 746-25",
      "name": "Galata Silver Lavabo",
      "size": "38x65cm",
      "listPrice": 10400.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-102.png",
      "searchText": "dlt 746-25 galata silver lavabo 38x65cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "103-dlt-751-15",
      "row": 103,
      "code": "DLT 751-15",
      "name": "Petrivi Beyaz Lavabo",
      "size": "H15xStandart",
      "listPrice": 10400.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-103.png",
      "searchText": "dlt 751-15 petrivi beyaz lavabo h15xstandart banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "104-dlt-751-23",
      "row": 104,
      "code": "DLT 751-23",
      "name": "Petrivi Bazalt Lavabo",
      "size": "H15xStandart",
      "listPrice": 10400.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-104.png",
      "searchText": "dlt 751-23 petrivi bazalt lavabo h15xstandart banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "105-dlt-751-25",
      "row": 105,
      "code": "DLT 751-25",
      "name": "Petrivi Silver Lavabo",
      "size": "H15xStandart",
      "listPrice": 10400.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-105.png",
      "searchText": "dlt 751-25 petrivi silver lavabo h15xstandart banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "106-dlt-752-01",
      "row": 106,
      "code": "DLT 752-01",
      "name": "Montana Klasik Lavabo",
      "size": "12x46x60cm",
      "listPrice": 10400.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-106.png",
      "searchText": "dlt 752-01 montana klasik lavabo 12x46x60cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "107-dlt-755-01",
      "row": 107,
      "code": "DLT 755-01",
      "name": "Sahra Klasik Lavabo",
      "size": "15x42cm",
      "listPrice": 7850.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-107.png",
      "searchText": "dlt 755-01 sahra klasik lavabo 15x42cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "108-dlt-756-01",
      "row": 108,
      "code": "DLT 756-01",
      "name": "Kurtuba Klasik Lavabo",
      "size": "15x42cm",
      "listPrice": 7850.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-108.png",
      "searchText": "dlt 756-01 kurtuba klasik lavabo 15x42cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "109-dlt-756-15",
      "row": 109,
      "code": "DLT 756-15",
      "name": "Kurtuba Beyaz Lavabo",
      "size": "15x42cm",
      "listPrice": 7850.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-109.png",
      "searchText": "dlt 756-15 kurtuba beyaz lavabo 15x42cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "110-dlt-757-01",
      "row": 110,
      "code": "DLT 757-01",
      "name": "Toledo Klasik Lavabo",
      "size": "12x46x60cm",
      "listPrice": 10400.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-110.png",
      "searchText": "dlt 757-01 toledo klasik lavabo 12x46x60cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "111-dlt-763-19",
      "row": 111,
      "code": "DLT 763-19",
      "name": "Vera Toros Lavabo",
      "size": "15x42cm",
      "listPrice": 14500.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-111.png",
      "searchText": "dlt 763-19 vera toros lavabo 15x42cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "112-dlt-767-01",
      "row": 112,
      "code": "DLT 767-01",
      "name": "Sitre Klasik Lavabo",
      "size": "Standart",
      "listPrice": 10400.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-112.png",
      "searchText": "dlt 767-01 sitre klasik lavabo standart banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "113-dlt-703-01",
      "row": 113,
      "code": "DLT 703-01",
      "name": "Kiev Klasik Lavabo",
      "size": "12x46x60cm",
      "listPrice": 10400.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-113.png",
      "searchText": "dlt 703-01 kiev klasik lavabo 12x46x60cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "114-dlt-636-01",
      "row": 114,
      "code": "DLT 636-01",
      "name": "Bosna Klasik Lavabo",
      "size": "12x46x60cm",
      "listPrice": 10400.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-114.png",
      "searchText": "dlt 636-01 bosna klasik lavabo 12x46x60cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "115-dlt-778-01",
      "row": 115,
      "code": "DLT 778-01",
      "name": "Niagara Klasik Lavabo",
      "size": "14x40x65cm",
      "listPrice": 10400.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-115.png",
      "searchText": "dlt 778-01 niagara klasik lavabo 14x40x65cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "116-dlt-778-13",
      "row": 116,
      "code": "DLT 778-13",
      "name": "Niagara Bardiglio Lavabo",
      "size": "14x40x65cm",
      "listPrice": 10400.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-116.png",
      "searchText": "dlt 778-13 niagara bardiglio lavabo 14x40x65cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "117-dlt-742-15",
      "row": 117,
      "code": "DLT 742-15",
      "name": "Glasgow Beyaz Lavabo",
      "size": "45x82cm",
      "listPrice": 39000.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-117.png",
      "searchText": "dlt 742-15 glasgow beyaz lavabo 45x82cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "118-dlt-742-01",
      "row": 118,
      "code": "DLT 742-01",
      "name": "Glasgow Klasik Lavabo",
      "size": "45x82cm",
      "listPrice": 39000.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-118.png",
      "searchText": "dlt 742-01 glasgow klasik lavabo 45x82cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "119-dlt-644-01",
      "row": 119,
      "code": "DLT 644-01",
      "name": "Zagreb Klasik Lavabo",
      "size": "42x82cm",
      "listPrice": 39000.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-119.png",
      "searchText": "dlt 644-01 zagreb klasik lavabo 42x82cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "120-dlt-644-23",
      "row": 120,
      "code": "DLT 644-23",
      "name": "Zagreb Bazalt Lavabo",
      "size": "42x82cm",
      "listPrice": 50000.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-120.png",
      "searchText": "dlt 644-23 zagreb bazalt lavabo 42x82cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "121-dlt-769-38",
      "row": 121,
      "code": "DLT 769-38",
      "name": "Babil Lavabo",
      "size": "42x82cm",
      "listPrice": 50000.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-121.png",
      "searchText": "dlt 769-38 babil lavabo 42x82cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "122-dlt-770-38",
      "row": 122,
      "code": "DLT 770-38",
      "name": "Sydney Miks Lavabo",
      "size": "42x82cm",
      "listPrice": 50000.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-122.png",
      "searchText": "dlt 770-38 sydney miks lavabo 42x82cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "123-dlt-753-15",
      "row": 123,
      "code": "DLT 753-15",
      "name": "Rumi Beyaz Kurna",
      "size": "25x43cm",
      "listPrice": 13200.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-123.png",
      "searchText": "dlt 753-15 rumi beyaz kurna 25x43cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "124-dlt-759-04",
      "row": 124,
      "code": "DLT 759-04",
      "name": "Belen Bej Kurna",
      "size": "25x43cm",
      "listPrice": 14500.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-124.png",
      "searchText": "dlt 759-04 belen bej kurna 25x43cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "125-dlt-759-15",
      "row": 125,
      "code": "DLT 759-15",
      "name": "Belen Beyaz Kurna",
      "size": "25x43cm",
      "listPrice": 13200.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-125.png",
      "searchText": "dlt 759-15 belen beyaz kurna 25x43cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "126-dlt-762-04",
      "row": 126,
      "code": "DLT 762-04",
      "name": "Köşe Kurna Bej",
      "size": "25x43cm",
      "listPrice": 13200.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-126.png",
      "searchText": "dlt 762-04 köşe kurna bej 25x43cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "127-dlt-762-15",
      "row": 127,
      "code": "DLT 762-15",
      "name": "Köşe Kurna Beyaz",
      "size": "25x43cm",
      "listPrice": 13200.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-127.png",
      "searchText": "dlt 762-15 köşe kurna beyaz 25x43cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "128-dlt-773-04",
      "row": 128,
      "code": "DLT 773-04",
      "name": "Santana Bej Kurna",
      "size": "25x43cm",
      "listPrice": 14500.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-128.png",
      "searchText": "dlt 773-04 santana bej kurna 25x43cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "129-dlt-773-15",
      "row": 129,
      "code": "DLT 773-15",
      "name": "Santana Beyaz Kurna",
      "size": "25x43cm",
      "listPrice": 14500.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-129.png",
      "searchText": "dlt 773-15 santana beyaz kurna 25x43cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "130-dlt-774-15",
      "row": 130,
      "code": "DLT 774-15",
      "name": "Elvas Beyaz Kurna",
      "size": "25x43cm",
      "listPrice": 14500.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-130.png",
      "searchText": "dlt 774-15 elvas beyaz kurna 25x43cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "131-dlt-707-04",
      "row": 131,
      "code": "DLT 707-04",
      "name": "Marsilya Kabil Bej Kurna",
      "size": "25x43cm",
      "listPrice": 14500.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-131.png",
      "searchText": "dlt 707-04 marsilya kabil bej kurna 25x43cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "132-dlt-707-13",
      "row": 132,
      "code": "DLT 707-13",
      "name": "Marsilya Bardiglio Kurna",
      "size": "25x43cm",
      "listPrice": 13200.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-132.png",
      "searchText": "dlt 707-13 marsilya bardiglio kurna 25x43cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "133-dlt-707-15",
      "row": 133,
      "code": "DLT 707-15",
      "name": "Marsilya Beyaz Kurna",
      "size": "25x43cm",
      "listPrice": 14500.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-133.png",
      "searchText": "dlt 707-15 marsilya beyaz kurna 25x43cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "134-dlt-707-19",
      "row": 134,
      "code": "DLT 707-19",
      "name": "Marsilya Siyah Kurna",
      "size": "25x43cm",
      "listPrice": 28500.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-134.png",
      "searchText": "dlt 707-19 marsilya siyah kurna 25x43cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "135-dlt-743-04",
      "row": 135,
      "code": "DLT 743-04",
      "name": "Finlandiya Haliç Bej Kurna",
      "size": "25x45cm",
      "listPrice": 13200.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-135.png",
      "searchText": "dlt 743-04 finlandiya haliç bej kurna 25x45cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "136-dlt-743-13",
      "row": 136,
      "code": "DLT 743-13",
      "name": "Finlandiya Bardiglio Kurna",
      "size": "43x43cm",
      "listPrice": 13200.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-136.png",
      "searchText": "dlt 743-13 finlandiya bardiglio kurna 43x43cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "137-dlt-743-15",
      "row": 137,
      "code": "DLT 743-15",
      "name": "Finlandiya Beyaz Kurna",
      "size": "25x43cm",
      "listPrice": 13200.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-137.png",
      "searchText": "dlt 743-15 finlandiya beyaz kurna 25x43cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "138-dlt-743-15s",
      "row": 138,
      "code": "DLT 743-15S",
      "name": "Finlandiya Şeker Kurna",
      "size": "25x43cm",
      "listPrice": 14500.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "",
      "searchText": "dlt 743-15s finlandiya şeker kurna 25x43cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "139-dlt-652-01",
      "row": 139,
      "code": "DLT 652-01",
      "name": "Monaco Klasik Duş Teknesi",
      "size": "3x90x20cm",
      "listPrice": 28500.0,
      "sourceCategory": "Banyo ve Lavabo",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "assets/row-139.png",
      "searchText": "dlt 652-01 monaco klasik duş teknesi 3x90x20cm banyo ve lavabo wash basins & kitchen sinks"
    },
    {
      "id": "140-antik-1036",
      "row": 140,
      "code": "Antik 1036",
      "name": "Antik Batarya",
      "size": "-",
      "listPrice": 7850.0,
      "sourceCategory": "Banyo Aksesuarları",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "",
      "searchText": "antik 1036 antik batarya - banyo aksesuarları wash basins & kitchen sinks"
    },
    {
      "id": "141-antik-1037",
      "row": 141,
      "code": "Antik 1037",
      "name": "Antik Batarya 2",
      "size": "-",
      "listPrice": 7850.0,
      "sourceCategory": "Banyo Aksesuarları",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "",
      "searchText": "antik 1037 antik batarya 2 - banyo aksesuarları wash basins & kitchen sinks"
    },
    {
      "id": "142-osmanl-1802",
      "row": 142,
      "code": "Osmanlı 1802",
      "name": "Osmanlı Kurna Bataryası",
      "size": "h118cm",
      "listPrice": 4920.0,
      "sourceCategory": "Banyo Aksesuarları",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "",
      "searchText": "osmanlı 1802 osmanlı kurna bataryası h118cm banyo aksesuarları wash basins & kitchen sinks"
    },
    {
      "id": "143-pedestal-batarya",
      "row": 143,
      "code": "Pedestal Batarya",
      "name": "Ayaklı Pedestal Bataryası",
      "size": "h118cm",
      "listPrice": 46800.0,
      "sourceCategory": "Banyo Aksesuarları",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "",
      "searchText": "pedestal batarya ayaklı pedestal bataryası h118cm banyo aksesuarları wash basins & kitchen sinks"
    },
    {
      "id": "144-cila-islak",
      "row": 144,
      "code": "CILA-ISLAK",
      "name": "Islak Görünümlü Cila",
      "size": "-",
      "listPrice": 3850.0,
      "sourceCategory": "Doğaltaş Bakımı",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "",
      "searchText": "cila-islak islak görünümlü cila - doğaltaş bakımı wash basins & kitchen sinks"
    },
    {
      "id": "145-cila-dogal",
      "row": 145,
      "code": "CILA-DOGAL",
      "name": "Doğal Görünümlü Cila",
      "size": "-",
      "listPrice": 3850.0,
      "sourceCategory": "Doğaltaş Bakımı",
      "mainCategory": "WASH BASINS & KITCHEN SINKS",
      "sortGroup": 3,
      "image": "",
      "searchText": "cila-dogal doğal görünümlü cila - doğaltaş bakımı wash basins & kitchen sinks"
    }
  ],
  "stats": {
    "productCount": 144,
    "withImages": 133,
    "withoutImages": 11
  }
};
